const USER_LOGGED = "USER_LOGGED";
const USER_LOGOUT = "USER_LOGOUT";
const SHOW_POPUP = "SHOW_POPUP";
const HIDDEN_POPUP = "HIDDEN_POPUP";

const URL_LOCAL = "http://localhost:8000/api";

export {USER_LOGGED, USER_LOGOUT, URL_LOCAL, SHOW_POPUP, HIDDEN_POPUP };