const URL_LOCAL = "http://localhost:8000/api";
const USER_LOGGED = "USER_LOGGED";
const SHOW_POPUP = "SHOW_POPUP";
const HIDDEN_POPUP = "HIDDEN_POPUP";





export {USER_LOGGED, URL_LOCAL, SHOW_POPUP, HIDDEN_POPUP };